[tool.poetry]
name = "flamecell"
version = "0.1.0"
description = "A python package to simulate the forest fire using cellular automaton"
authors = ["YiyangZhu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
